# Generated by Django 5.1 on 2024-09-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_image_blogpost_video_like'),
        ('blog', '0005_auto_20210906_1234'),
    ]

    operations = [
    ]
